version: '3'
services:
  postgres:
    image: postgres:9.6.2-alpine
    container_name: ${POSTGRES_NAME}
    ports:
      - "5432:5432"
    environment:
      KC_USER: ${KC_DB_OWNER}
      KC_PASSWORD: ${KC_DB_OWNER_PWD}
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
  keycloak:
    build: ./keycloak
    image: ${KC_TAG}
    container_name: ${KC_NAME}
    ports:
      - "8443:8443"
    depends_on:
      - postgres
    environment:
      POSTGRES_PORT_5432_TCP_ADDR: ${POSTGRES_NAME}
      POSTGRES_DATABASE: ${KC_DB}
      POSTGRES_USER: ${KC_DB_OWNER}
      POSTGRES_PASSWORD: ${KC_DB_OWNER_PWD}
         
  spaclient:
    image: spaclient
    build:
      context: ./SpaClient
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
    ports:
      - "8080:8080"

  spaidsrv:
    image: spaidsrv
    build:
      context: ./SpaIdSrv
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
    ports:
      - "2052:2052"

  #The productapi will be protected by identityserver
  productapi:
    image: productapi
    build:
      context: ./ProductApi
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT} 
    ports:
      - "2086:2086"
    #link required because the productapi loads the openidconfiguration from idsrv
    links:
      - spaidsrv:spaidsrv.org

  #The invoiceapi will be protected by Keycloak
  invoiceapi:
    image: invoiceapi
    build:
      context: ./InvoiceApi
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT} 
    ports:
      - "2095:2095"
    #link required because the invoiceapi loads the openidconfiguration from keycloak
    links:
      - keycloak:keycloak.com
volumes:
  pg_data:
